### ISSUE TITLE
Polygon orientation

### ISSUE THREAD

**Issue by exe-dealer** [wdtinc/mapbox-vector-tile-java#36] opened 2019-05-09 09:05 UTC
It seems that rings orientation in polygons is wrong. The specs says that exterior ring must be clockwise **in screen coordinates**. But orientation is flipped when JTS geometry is encoded to mvt, so preparation step should do the opposite orientation when it operates with JTS geometry. Mapbox encoder implementation does it like I say https://github.com/mapbox/geojson-vt/blob/d3bf094b1329dd84dcc8446ba407c9830469b808/src/tile.js#L113

Because of this issue extruded polygons are displayed inside out in mapboxgl viewer

![Screen Recording 2019-05-09 at 2 42 59 PM_1](https://user-images.githubusercontent.com/3988889/57440998-da88a980-726a-11e9-9c07-de18b13ef2f7.gif)

When I swapped orientation checks for exterior and interior rings in the following file then 3d polygons became normal
https://github.com/wdtinc/mapbox-vector-tile-java/blob/e5e3df3fc2260709e289f972a1348c0a1ea30339/src/main/java/com/wdtinc/mapbox_vector_tile/adapt/jts/JtsAdapter.java#L366
https://github.com/wdtinc/mapbox-vector-tile-java/blob/e5e3df3fc2260709e289f972a1348c0a1ea30339/src/main/java/com/wdtinc/mapbox_vector_tile/adapt/jts/JtsAdapter.java#L385

**Comment by ShibaBandit** [comment] 2019-05-09 17:15
I'll check this out

**Comment by zxp209** [comment] 2019-06-11 02:50
@ShibaBandit Hi,Did you checkout this issue?

**Comment by FelixCali** [comment] 2019-07-25 13:07
We had the same problem when testing with a tegola server as tile source. Should definetely be fixed to conform with the mvt-standard.

**Comment by ShibaBandit** [comment] 2019-08-01 21:10
So the method @exe-dealer mentioned takes in geometry in MVT coordinates (y-positive down). It then tries to ensure that the winding order is CW for the outer and CCW for the inner. I guess the issue is that the spec wants that ordering to be determined from the source geometry that does not have a positive Y down axis, so flipping the signs appears to handle this?

**Comment by ShibaBandit** [comment] 2019-08-02 15:06
Trying out some changes for this problem, one commit I saw on this issue thread is incomplete because it didn't flip the PolyRingClassifierV2_1#classifyRings check. Therefore unit tests would fail .

**Comment by ShibaBandit** [comment] 2019-08-02 15:32
Closing via #41

**Closed by ShibaBandit** 2019-08-02 15:32 UTC
Labels: bug
